### ISSUE TITLE
Get stdout and stderr of a task example is broken

### ISSUE THREAD

**Issue by bobrik** [andygrunwald/megos#7] opened 2016-05-12 16:31 UTC
```go
executor, _ := mesos.GetExecutorByID(framework.CompletedExecutors, taskID)
```

```
framework.CompletedExecutors undefined (type *megos.Framework has no field or method CompletedExecutors)
```

**Comment by andygrunwald** [comment] 2016-05-12 16:42
I really love that you report those issues. Right now is a local meetup in
Düsseldorf. Will fix it later, ok?
Thank you

Am Donnerstag, 12. Mai 2016 schrieb Ivan Babrou :

**Comment by bobrik** [comment] 2016-05-12 16:53
Sure, no pressure :)

**Comment by andygrunwald** [comment] 2016-05-27 15:03
The root cause of this bug was https://github.com/andygrunwald/megos/pull/3/files
The `CompletedExecutors` attribute was removed.
I added it again with a bunch of other missing attributes again in https://github.com/andygrunwald/megos/commit/c387c454a403d898a34d93413c642deb724d398b

The example was fixed in https://github.com/andygrunwald/megos/commit/dbeb637465281c33a7808015cbb02d85e3b0db55

Thank you!

**Closed** 2016-05-27 15:02 UTC
Labels: bug
